### ISSUE TITLE
logr v1.0.0-rc1 includes breaking changes

### ISSUE THREAD

**Issue by thockin** [wojas/genericr#2]
logr made BREAKING CHANGES for implementations to prep for 1.0.0

Here's the glogr PR that adopts the new logr API changes: go-logr/glogr#13 - this includes a bunch of perf-related changes too (sorry).

The changes are not THAT complicated. Please feel free to shout if they don't make sense.

**Comment by thockin** [comment]
https://github.com/go-logr/zapr/pull/28 is another example

**Comment by thockin** [comment]
logr v1.0.0 has been tagged.  No changes since rc1.

**Comment by wojas** [comment]
Thanks! This is still on my todo list, I expect to update it soon.

**Comment by pohly** [comment]
@wojas: it was suggested to [remove genericr](https://github.com/go-logr/logr/pull/150) from the go-logr documentation. Can you clarify whether this implementation is still maintained?

**Comment by pohly** [comment]
This seems to overlap in functionality with the funcr code in go-logr/logr itself. Perhaps it is not needed (anymore)?
